[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
etherscan-api-key = "${ETHERSCAN_API_KEY}"
private-key = "${PRIVATE_KEY}"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${MAINNET_RPC_URL}"
goerli = "https://goerli.infura.io/v3/${GOERLI_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
# See more config options https://github.com/foundry-rs/foundry/tree/master/config