[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
etherscan_api_key = "${ETHERSCAN_API_KEY}"

[rpc_endpoints]
mainnet = "https://mainnet.infura.io/v3/${RPC_MAINNET}"
goerli = "https://goerli.infura.io/v3/${RPC_GOERLI}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config